/*
Author: ToxaBes
*/        
_this addAction ["<t color='#F44336'><img image='\a3\ui_f\data\GUI\Cfg\Notifications\tridentEnemy_ca.paa' size='1.0'/> Уничтожить аванпост партизан</t>",{(_this select 0) setDamage 1;},[],18,true,true,"","((vehicle player) == player && playerSide == west)", 5];
_this addAction ["<t color='#FF8000'><img image='\A3\Soft_F\Quadbike_01\Data\UI\map_Quad_CA.paa' size='1.0'/> Вызвать квадрацикл</>", "scripts\misc\actions\baseVehicle_switch.sqf",["quadbike"],17,true,true,"",'((vehicle player) == player && playerSide == resistance) && adr_partizan_submenu', 5];    
_this addAction ["<t color='#FFBF00'><img image='\A3\soft_f_gamma\SUV_01\Data\UI\map_suv_01_CA.paa' size='1.0'/> Вызвать внедорожник (SUV)</>", "scripts\misc\actions\baseVehicle_switch.sqf",["suv"],16,true,true,"",'((vehicle player) == player && playerSide == resistance) && adr_partizan_submenu', 5];
_this addAction ["<t color='#BFFF00'><img image='\A3\soft_f\Offroad_01\Data\UI\map_offroad_01_CA.paa' size='1.0'/> Вызвать пикап</>", "scripts\misc\actions\baseVehicle_switch.sqf",["offroad"],15,true,true,"",'((vehicle player) == player && playerSide == resistance) && adr_partizan_submenu', 5];
_this addAction ["<t color='#01DFA5'><img image='\A3\Soft_F_Exp\Offroad_02\Data\UI\map_Offroad_02_base_CA.paa' size='1.0'/> Вызвать полноприводный джип</>", "scripts\misc\actions\baseVehicle_switch.sqf",["jeep"],14,true,true,"",'((vehicle player) == player && playerSide == resistance) && adr_partizan_submenu', 5];
_this addAction ["<t color='#2196F3'><img image='\a3\ui_f\data\map\VehicleIcons\iconShip_ca.paa' size='1.0'/> Вызвать лодку</>", "scripts\misc\actions\baseVehicle_switch.sqf",["ship"],13,true,true,"",'((vehicle player) == player && playerSide == resistance) && adr_partizan_submenu', 5];
_this addAction ["<t color='#BDBDBD'><img image='\a3\ui_f\data\Map\VehicleIcons\iconCar_ca.paa' size='1.0'/> Вызвать технику</>", {[] spawn {adr_partizan_submenu = true; sleep 20, adr_partizan_submenu = false;}},[],6,true,false,"",'((vehicle player) == player && playerSide == resistance) && !adr_partizan_submenu', 5];
_this addAction ["<t color='#BDBDBD'><img image='\a3\ui_f\data\Map\Diary\Icons\taskFailed_ca.paa' size='1.0'/> Отмена</>", {adr_partizan_submenu = false;},[],6,true,false,"",'((vehicle player) == player && playerSide == resistance) && adr_partizan_submenu', 5];