_center = _this select 0;
["<t color='#7FDA0B' size = '.48'>Сброс боеприпасов...</t>", 0, 0.8, 3, 0.5, 0] spawn BIS_fnc_dynamicText;
_radius = 100;
_height = 300;
_pos = [
	(_center select 0) - _radius + (2 * random _radius),
	(_center select 1) - _radius + (2 * random _radius),
	_height
];
_parachute = createVehicle ["B_Parachute_02_F", [100, 100, 200], [], 0, 'FLY'];
_parachute setPos _pos;
_parachute allowDamage false;
_cargo = createVehicle ["B_supplyCrate_F", position _parachute, [], 0, 'NONE'];
_cargo attachTo [_parachute, [0, 0, -0.4]];
_cargo allowDamage false;
_light = createVehicle ["Chemlight_blue", position _parachute, [], 0, 'NONE'];
_light attachTo [_cargo, [0, 0, 0]];
_smoke1 = "SmokeShellBlue" createVehicle [getPos _cargo select 0, getPos _cargo select 1, 3];
_smoke1 attachTo [_cargo, [0, 0, 0]];
clearWeaponCargoGlobal _cargo;
clearMagazineCargoGlobal _cargo;
_cargo addMagazineCargoGlobal ["30Rnd_556x45_Stanag", 5];
_cargo addMagazineCargoGlobal ["30Rnd_556x45_Stanag_Tracer_Red", 15];
_cargo addMagazineCargoGlobal ["20Rnd_556x45_UW_mag", 10];
_cargo addMagazineCargoGlobal ["30Rnd_65x39_caseless_green", 5];
_cargo addMagazineCargoGlobal ["30Rnd_65x39_caseless_green_mag_Tracer", 15];
_cargo addMagazineCargoGlobal ["5Rnd_127x108_APDS_Mag", 15];
_cargo addMagazineCargoGlobal ["7Rnd_408_Mag", 15];
_cargo addMagazineCargoGlobal ["10Rnd_93x64_DMR_05_Mag", 20];
_cargo addMagazineCargoGlobal ["10Rnd_127x54_Mag", 20];
_cargo addMagazineCargoGlobal ["10Rnd_338_Mag", 20];
_cargo addMagazineCargoGlobal ["20Rnd_762x51_Mag", 20];
_cargo addMagazineCargoGlobal ["10Rnd_762x54_Mag", 20];
_cargo addMagazineCargoGlobal ["30Rnd_65x39_caseless_mag", 5];
_cargo addMagazineCargoGlobal ["30Rnd_65x39_caseless_mag_Tracer", 25];
_cargo addMagazineCargoGlobal ["100Rnd_65x39_caseless_mag_Tracer", 15];
_cargo addMagazineCargoGlobal ["150Rnd_762x54_Box_Tracer", 10];
_cargo addMagazineCargoGlobal ["200Rnd_65x39_cased_Box_Tracer", 10];
_cargo addMagazineCargoGlobal ["150Rnd_93x64_Mag", 10];
_cargo addMagazineCargoGlobal ["130Rnd_338_Mag", 10];
_cargo addMagazineCargoGlobal ["SatchelCharge_Remote_Mag", 2];
_cargo addMagazineCargoGlobal ["DemoCharge_Remote_Mag", 4];
_cargo addMagazineCargoGlobal ["HandGrenade", 6];
_cargo addMagazineCargoGlobal ["SmokeShell", 16];
_cargo addMagazineCargoGlobal ["SmokeShellGreen", 16];
_cargo addMagazineCargoGlobal ["SmokeShellBlue", 16];
_cargo addMagazineCargoGlobal ["1Rnd_HE_Grenade_shell", 16];
_cargo addMagazineCargoGlobal ["RPG32_HE_F", 6];
_cargo addMagazineCargoGlobal ["RPG32_F", 6];
_cargo addMagazineCargoGlobal ["Titan_AT", 12];
_cargo addMagazineCargoGlobal ["Titan_AA", 12];
_cargo addMagazineCargoGlobal ["Laserbatteries", 5];
_cargo addItemCargoGlobal ["FirstAidKit", 30];
_cargo addItemCargoGlobal ["Medikit", 2];
_cargo addItemCargoGlobal ["ToolKit", 2];
_cargo addBackpackCargoGlobal ["B_AssaultPack_mcamo", 2];
_cargo addBackpackCargoGlobal ["B_Kitbag_mcamo_Eng", 2];
[_cargo, _light, _smoke1] spawn {
    _cargo = _this select 0;
    _light = _this select 1;
    _smoke1 = _this select 2;
    _smoke2 = _this select 3;
    sleep 15;
    hqSideChat = "Боеприпасы сброшены!"; publicVariable "hqSideChat"; [WEST, "HQ"] sideChat hqSideChat;
    _smoke2 = createVehicle ["SmokeShellBlue", position _cargo, [], 0, 'NONE'];
    _smoke2 attachTo [_cargo, [0, 0, 0.5]];
	waitUntil {(getPos _cargo select 2) < 2};
    detach _cargo;
    sleep 5;
    _smoke3 = createVehicle ["SmokeShellBlue", position _cargo, [], 0, 'NONE'];
    _smoke3 attachTo [_cargo, [0, 0, 0.5]];
    sleep 900;
    if (!isNil {_cargo}) then {deleteVehicle _cargo};
    if (!isNil {_light}) then {deleteVehicle _light};
    if (!isNil {_smoke1}) then {deleteVehicle _smoke1};
    if (!isNil {_smoke2}) then {deleteVehicle _smoke2};
    if (!isNil {_smoke3}) then {deleteVehicle _smoke3};
};
